name: Deploy Schemas
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Schema Registry
        uses: Saurav0310/Schema/.github/actions/schema-registry-deploy@main
        with:
          schema-dir: 'kafka/schemas'
          registry-url: ${{ secrets.SCHEMA_REGISTRY_URL }}
          api-key: ${{ secrets.SCHEMA_REGISTRY_API_KEY }}
          api-secret: ${{ secrets.SCHEMA_REGISTRY_API_SECRET }}
